version: 2.1

workflows:
  pr_build:
      jobs:
        - cancel_redundant_builds:
            name: cancel previous jobs
            filters: { branches: { ignore: [main] } }

        - opg-metrics/terraform_command:
            name: lint shared terraform
            workspace: development
            configuration_path: account
            terraform_command: validate
            filters: { branches: { ignore: [main] } }
            requires: [cancel previous jobs]

        - opg-metrics/terraform_command:
            name: lint service terraform
            workspace: development
            configuration_path: environment
            terraform_command: validate
            filters: { branches: { ignore: [main] } }
            requires: [cancel previous jobs]

        - opg-metrics/terraform_command:
            name: plan shared terraform
            workspace: development
            configuration_path: account
            terraform_command: plan
            filters: { branches: { ignore: [main] } }
            requires: [
              lint shared terraform,
              ]

        - opg-metrics/terraform_command:
            name: plan service terraform
            workspace: development
            configuration_path: environment
            terraform_command: plan
            filters: { branches: { ignore: [main] } }
            requires: [
              lint service terraform,
              ]

  path_to_live:
      jobs:
        - opg-metrics/terraform_command:
            name: apply shared terraform
            workspace: development
            configuration_path: account
            terraform_command: apply
            filters: { branches: { only: [main] } }

        - opg-metrics/terraform_command:
              name: apply service terraform
              workspace: development
              configuration_path: environment
              terraform_command: apply
              filters: { branches: { only: [main] } }
              requires: [
                apply shared terraform,
                ]



orbs:
  slack: circleci/slack@3.3.0
  opg-metrics:
    executors:
      terraform:
        docker: [image: hashicorp/terraform:1.0.3]
        resource_class: small

    jobs:
      terraform_command:
        executor: terraform
        parameters:
          workspace:
            description: Terraform workspace name
            type: string
          configuration_path:
            description: Terraform workspace name
            type: string
          terraform_command:
            description: Terraform workspace name
            type: string
        environment:
          TF_WORKSPACE: "<<parameters.workspace>>"
          TF_CLI_ARGS_apply: "-auto-approve"
        steps:
          - checkout
          - run:
              name: terraform <<parameters.terraform_command>> <<parameters.configuration_path>> <<parameters.workspace>>
              command: |
                terraform --version
                cd ~/project/terraform/<<parameters.configuration_path>>
                terraform init
                terraform <<parameters.terraform_command>>


jobs:
  cancel_redundant_builds:
    docker:
      - image: circleci/python
    resource_class: small
    steps:
      - checkout
      - run:
          name: Cancel Redundant Builds
          command: |
            python scripts/pipeline/cancel_previous_jobs/cancel_redundant_builds.py \
            --circle_project_username ${CIRCLE_PROJECT_USERNAME} \
            --circle_project_reponame ${CIRCLE_PROJECT_REPONAME} \
            --circle_branch ${CIRCLE_BRANCH} \
            --circle_builds_token ${CIRCLECI_API_KEY} \
            --terms_to_waitfor "plan_shared_terraform,apply_environment_terraform"
