services:
  shiptometrics:
    image: ship-to-opg-metrics
    build:
      context: ./ship-to-opg-metrics
      dockerfile: Dockerfile
      target: test
    ports:
      - 9000:8080
    volumes:
      - type: bind
        source: ./ship-to-opg-metrics
        target: /ship-to-opg-metrics
