name: "[Analysis - Infrastructure] TFSec Pull Request Feedback"

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  schedule:
    # 8am every wednesday
    - cron: '0 8 * * 3'

  
permissions:
  contents: read
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none
jobs:
  sast_to_github_security:
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-application-codeql-sast-to-github-security.yml@main
    with:
      application_languages: '["python"]'
