name: "[Analysis - Infrastructure] TFSec Pull Request Feedback"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, master ]
    paths: ["**.tf"]
  
permissions:
  contents: read
  security-events: none
  pull-requests: write
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none
jobs:
  tfsec_pr_feedback:
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-infrastructure-tfsec-pr-feedback.yml@main
    with:
      terraform_path: '["terraform/account", "terraform/environment"]'
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}
