name: Build and Publish Apache Flink kinesis connector

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        id: checkout_code
        with:
          repository: 'awslabs/amazon-timestream-tools'
          ref: 'mainline'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          ls
          cd integrations/flink_connector/sample-kinesis-to-timestream-app
          mvn clean compile && mvn package
      - name: Upload Apache Flink Jar
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: kinesis-to-timestream-app
          path: integrations/flink_connector/sample-kinesis-to-timestream-app/target/sample-kinesis-to-timestream-app-0.1-SNAPSHOT.jar

# Built jar file in integrations/flink_connector/sample-kinesis-to-timestream-app/target/sample-kinesis-to-timestream-app-0.1-SNAPSHOT.jar
