name: Build and Publish Apache Flink kinesis connector

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Tuesday, at 09:20 UTC
    - cron: '20 9 * * 2'
# Based on https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
