name: Build and Publish Apache Flink kinesis connector

on:
  workflow_call:
    outputs:
      artifact_name:
        description: "Uploaded artifact name"
        value: ${{ jobs.build.outputs.artifact_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        id: checkout_code
        with:
          repository: 'awslabs/amazon-timestream-tools'
          ref: 'mainline'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        id: maven_build
        run: |
          cd integrations/flink_connector/sample-kinesis-to-timestream-app
          mvn clean compile && mvn package -Djar.finalName=opg-metrics-kinesis-to-timestream-app
          echo ::set-output name=artifact_name::opg-metrics-kinesis-to-timestream-app
      - name: Upload Apache Flink Jar
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.maven_build.outputs.artifact_name }}
          path: integrations/flink_connector/sample-kinesis-to-timestream-app/target/${{ steps.maven_build.outputs.artifact_name }}.jar
    outputs:
      artifact_name: ${{ steps.maven_build.outputs.artifact_name }}
