name: Build and Publish Go Connector Lambda
on:
  workflow_call:
    outputs:
      artifact_name:
        description: "Uploaded artifact name"
        value: ${{ jobs.build.outputs.artifact_name }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: '^1.18.3'
      - name: Build with Go
        id: go_build
        run: |
          cd kinesis_timestream_connector/connector
          GOARCH=amd64 GOOS=linux CGO_ENABLED=0  go build -tags lambda.norpc -o bootstrap main.go
          echo ::set-output name=artifact_name::bootstrap
      - name: Upload Go executable
        id: upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ steps.go_build.outputs.artifact_name }}
          path: kinesis_timestream_connector/connector/${{ steps.go_build.outputs.artifact_name }}
    outputs:
      artifact_name: ${{ steps.go_build.outputs.artifact_name }}
