on:
  workflow_call:
    inputs:
      lambda_names:
        description: "The name of the lambda Docker container"
        required: true
        type: string
      tag:
        description: "Tag for docker image"
        required: true
        type: string
    secrets:
      aws_access_key_id_actions:
        required: true
      aws_secret_access_key_actions:
        required: true
      snyk_opg_org_token:
        required: true

jobs:
  docker_build_scan_push:
    name: Build, Scan and Push Lambdas
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lambda_name: ${{ fromJSON(inputs.lambda_names) }}
        include:
          - lambda_name: clsf-to-sqs
            scan_id: clsf_to_sqs
          - lambda_name: ship-to-opg-metrics
            scan_id: ship_to_opg_metrics
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Build Container
        id: build_container
        run: |
          docker build --file lambda/${{ matrix.lambda_name }}/Dockerfile --target production --tag ${{ matrix.lambda_name }}:latest .

      - name: Snyk scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@8dea82fc8b8e7ffca431f0fb83848d523147ccd8 # v4.5.0
        with:
          SNYK_TEST_IMAGE: ${{ matrix.lambda_name }}:latest
          SNYK_TOKEN: ${{ secrets.snyk_opg_org_token }}
          scan_id: ${{ matrix.scan_id }}

      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
        if: always()
        with:
          sarif_file: 'test-results/${{ matrix.scan_id }}_snyk.sarif'
          category: ${{ matrix.scan_id }}

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@e8b481e524a99f37fbd39fdc1dcb3341ab091367 # v1
        if: ${{ github.actor != 'dependabot[bot]' }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_actions }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key_actions }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::311462405659:role/opg-metrics-ci
          role-duration-seconds: 900
          role-session-name: OPGMetricsECRGithubAction
      - name: ECR Login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          registries: 311462405659
      - name: Push Container
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: opg-metrics/${{ matrix.lambda_name }}
        run: |
          docker tag ${{ matrix.lambda_name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.tag }}
          if [ $BRANCH_NAME == "main" ]; then
            docker tag ${{ matrix.lambda_name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ inputs.tag }}
            docker tag ${{ matrix.lambda_name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          fi
            docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
