name: "[Workflow] Path To Live"

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  branch_name:
    uses: ./.github/workflows/data-parse-branch-name.yml

  build_go:
    name: Build Go
    uses: ./.github/workflows/build_and_upload_go_connector_artifact_job.yml

  test_lambdas:
    name: Test Lambda
    uses: ./.github/workflows/python_build_test_job.yml
    with:
      lambda_name: '["ship-to-opg-metrics", "clsf-to-sqs"]'

  create_tags:
    name: Create Tags
    needs: ['branch_name', 'test_lambdas']
    uses: ./.github/workflows/tags_job.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.raw_branch_name }}
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}

  docker_build_scan_push:
    name: Build, Scan and Push
    needs: ['create_tags']
    uses: ./.github/workflows/docker_job.yml
    with:
      lambda_names: '["ship-to-opg-metrics", "clsf-to-sqs"]'
      tag: ${{ needs.create_tags.outputs.version_tag }}
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  tfsec:
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-infrastructure-tfsec-pr-feedback.yml@main
    with:
      terraform_path: '["terraform/account", "terraform/environment"]'
      soft_fail: true
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}

  terraform_account_workflow:
    name: Terraform Account
    needs: ['tfsec', 'docker_build_scan_push']
    uses: ./.github/workflows/terraform_plan_job.yml
    with:
      terraform_path: 'terraform/account'
      workspace: development
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  terraform_environment_workflow:
    name: Terraform Environment
    needs: ['terraform_account_workflow', 'build_go']
    uses: ./.github/workflows/terraform_plan_job.yml
    with:
      terraform_path: 'terraform/environment'
      workspace: development
      download_artifact: true
      download_go_artifact_name: ${{ needs.build_go.outputs.artifact_name }}
      download_go_artifact_path_name: 'kinesis-go-application'
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
