name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  test_ship_to_opg_metrics:
    name: Test ship-to-opg-metrics Lambda
    uses: ./.github/workflows/python_build_test_job.yml
    with:
      lambda_name: ship-to-opg-metrics

  test_clsf_to_sqs:
    name: Test clsf-to-sqs Lambda
    uses: ./.github/workflows/python_build_test_job.yml
    with:
      lambda_name: clsf-to-sqs

  docker_build_scan_push_ship_to_opg_metrics:
    name: Build, Scan and Push ship-to-opg-metrics
    needs: [
      'test_ship_to_opg_metrics',
      'test_clsf_to_sqs',
    ]
    uses: ./.github/workflows/python_build_test_job.yml
    with:
      lambda_name: ship-to-opg-metrics
    secrets: inherit

  docker_build_scan_push_clsf_to_sqs:
    name: Build, Scan and Push clsf-to-sqs
    needs: [
      'test_ship_to_opg_metrics',
      'test_clsf_to_sqs',
    ]
    uses: ./.github/workflows/python_build_test_job.yml
    with:
      lambda_name: clsf-to-sqs
    secrets: inherit

  tfsec_account:
    name: TFSec Static analysis account
    uses: ./.github/workflows/tfsec_job.yml
    with:
      terraform_path: 'terraform/account'
    secrets: inherit

  tfsec_environment:
    name: TFSec Static analysis environment
    uses: ./.github/workflows/tfsec_job.yml
    with:
      terraform_path: 'terraform/environment'
    secrets: inherit

  terraform_plan_workflow_account:
    name: Terraform Account Plan
    needs: [
      'tfsec_account',
      'tfsec_environment'
    ]
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      terraform_path: 'terraform/account'
    secrets: inherit

  terraform_plan_workflow_environment:
    name: Terraform Environment Plan
    needs: [
      'tfsec_account',
      'tfsec_environment'
    ]
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      terraform_path: 'terraform/environment'
    secrets: inherit
