name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  test_lambdas:
    name: Test Lambda
    uses: ./.github/workflows/python_build_test_job.yml
    with:
      lambda_name: '["ship-to-opg-metrics", "clsf-to-sqs"]'

  docker_build_scan_push:
    name: Build, Scan and Push
    needs: ['test_lambdas']
    uses: ./.github/workflows/python_build_test_job.yml
    with:
      lambda_name: '["ship-to-opg-metrics", "clsf-to-sqs"]'
    secrets: inherit

  tfsec:
    name: TFSec Static analysis
    uses: ./.github/workflows/tfsec_job.yml
    with:
      terraform_path: '["terraform/account", "terraform/environment"]'
    secrets: inherit

  terraform_plan_workflow:
    name: Terraform Account Plan
    needs: ['tfsec']
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      terraform_path: '["terraform/account", "terraform/environment"]'
    secrets: inherit
