on:
  workflow_call:
    inputs:
      lambda_name:
        description: 'The name of the lambdas to run'
        required: true
        type: string

jobs:
  test:
    name: Test Lambdas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda_name: ${{ fromJSON(inputs.lambda_name) }}
    steps:
      - name: Check out code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Python 3.8
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mock
          cd lambda/${{ matrix.lambda_name }}/src
          pip install -r requirements_dev.txt

      - name: Test with pytest
        run: |
          cd lambda/${{ matrix.lambda_name }}/src
          pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.lambda_name }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pytest-results-${{ matrix.lambda_name }}
          path: lambda/${{ matrix.lambda_name }}/src/junit/test-results-${{ matrix.lambda_name }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
