on:
  workflow_call:
    inputs:
      lambda_name:
        description: 'The name of the lambda to run'
        required: true
        type: string

jobs:
  test:
    name: Test Lambdas
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mock
          cd lambda/${{ inputs.lambda_name }}/src
          pip install -r requirements_dev.txt

      - name: Test with pytest
        run: |
          cd lambda/${{ inputs.lambda_name }}/src
          pytest --doctest-modules --junitxml=junit/test-results-${{ inputs.lambda_name }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ inputs.lambda_name }}
          path: lambda/${{ inputs.lambda_name }}/src/junit/test-results-${{ inputs.lambda_name }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
