on:
  workflow_call:
    inputs:
      terraform_path:
        description: 'The names of the terraform paths'
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
          required: true

jobs:
  tfsec:
    name: TFSec Static analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_path: ${{ fromJSON(inputs.terraform_path) }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: tfsec with pr comments
        uses: tfsec/tfsec-pr-commenter-action@v1.2.0
        with:
          working_directory: ${{ matrix.terraform_path }}
          github_token: ${{secrets.GITHUB_TOKEN}}
      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@v0.1.3
        with:
          sarif_file: tfsec.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
